# Generated by Django 4.2.26 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artigo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', blank=True),
        ),
    ]
